export const Notification = [
  {
    name: "ComapnyA",
    role: "Frontend",
    time: "11m",
    color: true,
  },
  {
    name: "ComapnyB",
    role: "Backend",
    time: "1h",
    color: false,
  },
  {
    name: "ComapnyC",
    role: "FullStack",
    time: "50m",
    color: true,
  },
  {
    name: "ComapnyD",
    role: "Senior Frontend",
    time: "1w",
    color: false,
  },
];
export const Network = [
  {
    id: 1,
    name: "Ms Aoife Kramer",
    role: "Frontend",
    company: "CompanyA",
    backImg: "https://source.unsplash.com/160x90/?nature,water",
    proImg: "https://source.unsplash.com/160x160/?women,face",
    con: "Connect",
  },
  {
    id: 2,
    name: "Saffron Lin",
    role: "Frontend",
    company: "CompanyB",
    backImg: "https://source.unsplash.com/160x90/?nature,fire",
    proImg: "https://source.unsplash.com/160x160/?women,face",
    con: "Connect",
  },
  {
    id: 3,
    name: "Osian Mcgee",
    role: "Frontend",
    company: "CompanyC",
    backImg: "https://source.unsplash.com/160x90/?nature,forest",
    proImg: "https://source.unsplash.com/160x160/?people,face",
    con: "Connect",
  },
  {
    id: 4,
    name: "Eva Krueger",
    role: "Frontend",
    company: "CompanyD",
    backImg: "https://source.unsplash.com/160x90/?nature,sun",
    proImg: "https://source.unsplash.com/160x160/?women,face",
    con: "Connect",
  },
  {
    id: 5,
    name: "Declan Arroyo",
    role: "Frontend",
    company: "CompanyE",
    backImg: "https://source.unsplash.com/160x90/?nature,earth",
    proImg: "https://source.unsplash.com/160x160/?men,face",
    con: "Connect",
  },
  {
    id: 6,
    name: "Declan Arroyo",
    role: "Frontend",
    company: "CompanyF",
    backImg: "https://source.unsplash.com/160x90/?nature,wind",
    proImg: "https://source.unsplash.com/160x160/?people,face",
    con: "Connect",
  },
];
export const jobs = [
  {
    id: 1,
    name: "Frontend Developer",
    company: "Company A",
    location: "Helsinki",
    time: "1 day ago",
  },
  {
    id: 2,
    name: "Backend Developer",
    company: "Company B",
    location: "Stockholm",
    time: "3 days ago",
  },
  {
    id: 3,
    name: "Fulstack Developer",
    company: "Company C",
    location: "Milan",
    time: "4 days ago",
  },
  {
    id: 4,
    name: "Junior Software Engineer",
    company: "Company D",
    location: "New York",
    time: "6 days ago",
  },
  {
    id: 5,
    name: "Senior Frontend Developer",
    company: "Company F",
    location: "Helsinki",
    time: "1 week ago",
  },
];
export const jobsSearch = [
  {
    id: 1,
    name: "frontend",
    qty: 3,
    location: "Sweden",
    level: "entry",
  },
  {
    id: 2,
    name: "backend",
    qty: 2,
    location: "Finland",
    level: "entry",
  },
  {
    id: 3,
    name: "fullstack",
    qty: 5,
    location: "Italy",
    level: "entry",
  },
];
