export const Notification = [
  {
    name: "ComapnyA",
    role: "Frontend",
    time: "11m",
    color: true,
  },
  {
    name: "ComapnyB",
    role: "Backend",
    time: "1h",
    color: false,
  },
  {
    name: "ComapnyC",
    role: "FullStack",
    time: "50m",
    color: true,
  },
  {
    name: "ComapnyD",
    role: "Senior Frontend",
    time: "1w",
    color: false,
  },
];
export const Network = [
  {
    id: 1,
    name: "Ms Aoife Kramer",
    role: "Frontend",
    company: "CompanyA",
    backImg: "https://source.unsplash.com/160x90/?nature,water",
    proImg: "https://source.unsplash.com/160x160/?women,face",
    con: "Connected",
  },
  {
    id: 2,
    name: "Saffron Lin",
    role: "Frontend",
    company: "CompanyB",
    backImg: "https://source.unsplash.com/160x90/?nature,fire",
    proImg: "https://source.unsplash.com/160x160/?women,face",
    con: "Connected",
  },
  {
    id: 3,
    name: "Osian Mcgee",
    role: "Frontend",
    company: "CompanyC",
    backImg: "https://source.unsplash.com/160x90/?nature,forest",
    proImg: "https://source.unsplash.com/160x160/?people,face",
    con: "Connected",
  },
  {
    id: 4,
    name: "Eva Krueger",
    role: "Frontend",
    company: "CompanyD",
    backImg: "https://source.unsplash.com/160x90/?nature,sun",
    proImg: "https://source.unsplash.com/160x160/?women,face",
    con: "Connect",
  },
  {
    id: 5,
    name: "Declan Arroyo",
    role: "Frontend",
    company: "CompanyE",
    backImg: "https://source.unsplash.com/160x90/?nature,earth",
    proImg: "https://source.unsplash.com/160x160/?men,face",
    con: "Connect",
  },
  {
    id: 6,
    name: "Declan Arroyo",
    role: "Frontend",
    company: "CompanyF",
    backImg: "https://source.unsplash.com/160x90/?nature,wind",
    proImg: "https://source.unsplash.com/160x160/?people,face",
    con: "Connect",
  },
];
